name: sina
description: "مشاور همراه سینا"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.1.5
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.13.1
  flutter_inappwebview: ^6.1.5
  flutter_custom_tabs: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/images/sina1.png
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/sina.png

  fonts:
    - family: Far_Homa
      fonts:
        - asset: assets/fonts/Far_Homa.ttf
