name: sina
description: "مشاور همراه سینا"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.13.1
  flutter_inappwebview: ^6.1.5
  flutter_custom_tabs: ^2.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/sina.png

  fonts:
    - family: B-NAZANIN
      fonts:
        - asset: assets/fonts/B-NAZANIN.TTF
